// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateOffer() {
  return window['go']['main']['App']['CreateOffer']();
}

export function SetAnswer(arg1) {
  return window['go']['main']['App']['SetAnswer'](arg1);
}
