// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptAnswer(arg1) {
  return window['go']['main']['App']['AcceptAnswer'](arg1);
}

export function AcceptOffer(arg1) {
  return window['go']['main']['App']['AcceptOffer'](arg1);
}

export function CreateOffer() {
  return window['go']['main']['App']['CreateOffer']();
}

export function ExportToFile(arg1, arg2) {
  return window['go']['main']['App']['ExportToFile'](arg1, arg2);
}

export function ImportFromFile(arg1) {
  return window['go']['main']['App']['ImportFromFile'](arg1);
}

export function StartHostProxy(arg1, arg2) {
  return window['go']['main']['App']['StartHostProxy'](arg1, arg2);
}

export function StartJoinerProxy(arg1, arg2) {
  return window['go']['main']['App']['StartJoinerProxy'](arg1, arg2);
}
