// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {webrtc} from '../models';

export function AcceptAnswer(arg1:string):Promise<void>;

export function AcceptOffer(arg1:string):Promise<string>;

export function CreateOffer():Promise<string>;

export function ExportToFile(arg1:string,arg2:string):Promise<void>;

export function ImportFromFile(arg1:string):Promise<string>;

export function StartHostProxy(arg1:webrtc.DataChannel,arg2:string):Promise<void>;

export function StartJoinerProxy(arg1:webrtc.DataChannel,arg2:string):Promise<void>;
